// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/user": {
            "get": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Получение списка юзеров со всеми данными.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получение списка юзеров. [Только админ]",
                "operationId": "admin-user-list",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "example": [
                            "student"
                        ],
                        "description": "user roles (accepted: \"teacher\", \"student\")",
                        "name": "roles",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.User"
                            }
                        }
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Создание нового юзера и профиля для него со всеми данными.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Создание нового юзера. [Только админ]",
                "operationId": "admin-user-create",
                "parameters": [
                    {
                        "description": "userBody",
                        "name": "userBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.userBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "группа не найдена"
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    },
                    "404": {
                        "description": "группа не найдена"
                    },
                    "409": {
                        "description": "пользователь с введенным логином уже существует"
                    }
                }
            }
        },
        "/admin/user/{id}": {
            "get": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Получение юзера со всеми данными по его id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получение юзера по id. [Только админ]",
                "operationId": "admin-user-read",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID юзера",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    },
                    "404": {
                        "description": "пользователь не найден"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Удаление юзера и его профиля по его id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Удаление юзера по id. [Только админ]",
                "operationId": "admin-user-delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID юзера",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    },
                    "404": {
                        "description": "пользователь не найден"
                    }
                }
            }
        },
        "/admin/user/{id}/password": {
            "put": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Смена пароля юзера по его id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Смена пароля юзера. [Только админ]",
                "operationId": "admin-user-password-update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID юзера",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "updatePasswordAdminBody",
                        "name": "updatePasswordAdminBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updatePasswordAdminBody"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    },
                    "404": {
                        "description": "пользователь не найден"
                    }
                }
            }
        },
        "/admin/user/{id}/profile": {
            "put": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Полное обновление профиля юзера по его id.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Обновление профиля юзера по id. [Только админ]",
                "operationId": "admin-user-profile-update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID юзера",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "profileBody",
                        "name": "profileBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.profileBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    },
                    "404": {
                        "description": "пользователь не найден"
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Вход для существующего юзера по логину и паролю.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход для юзера.",
                "operationId": "auth-login",
                "parameters": [
                    {
                        "description": "authBody",
                        "name": "authBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.authBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "неверный пароль"
                    },
                    "404": {
                        "description": "пользователь с введенным логином не найден"
                    }
                }
            }
        },
        "/auth/private/logout": {
            "post": {
                "security": [
                    {
                        "JWTRefresh": []
                    }
                ],
                "description": "Выход юзера (помещение refresh токена юзера в черный список).",
                "tags": [
                    "auth"
                ],
                "summary": "Выход юзера.",
                "operationId": "auth-private-logout",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    },
                    "403": {
                        "description": "токен в черном списке"
                    }
                }
            }
        },
        "/auth/private/obtain": {
            "post": {
                "security": [
                    {
                        "JWTRefresh": []
                    }
                ],
                "description": "Получение нового access токена по данному refresh токену из cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Получение access токена.",
                "operationId": "auth-private-obtain",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    },
                    "403": {
                        "description": "токен в черном списке"
                    }
                }
            }
        },
        "/example/admin": {
            "get": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Проверочный эндпоинт с доступом только для админов.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "Проверка. Только админы.",
                "operationId": "example-admin",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.exampleData"
                        }
                    },
                    "401": {
                        "description": "Неверный токен (пустой, истекший или неверный формат)"
                    },
                    "404": {
                        "description": "Юзер не админ, доступ запрещён"
                    }
                }
            }
        },
        "/example/free": {
            "get": {
                "description": "Проверочный эндпоинт с доступом абсолютно всем.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "Проверка. Все.",
                "operationId": "example-free",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.exampleData"
                        }
                    }
                }
            }
        },
        "/example/private": {
            "get": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Проверочный эндпоинт с доступом только для авторизованных юзеров.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "Проверка. Только авторизованные.",
                "operationId": "example-private",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.exampleData"
                        }
                    },
                    "401": {
                        "description": "Неверный токен (пустой, истекший или неверный формат)"
                    },
                    "404": {
                        "description": "Юзер не авторизован, доступ запрещён"
                    }
                }
            }
        },
        "/example/student": {
            "get": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Проверочный эндпоинт с доступом только для студентов.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "Проверка. Только студенты.",
                "operationId": "example-student",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.exampleData"
                        }
                    },
                    "401": {
                        "description": "Неверный токен (пустой, истекший или неверный формат)"
                    },
                    "404": {
                        "description": "Юзер не студент, доступ запрещён"
                    }
                }
            }
        },
        "/example/teacher": {
            "get": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Проверочный эндпоинт с доступом только для преподавателей.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "Проверка. Только преподаватели.",
                "operationId": "example-teacher",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.exampleData"
                        }
                    },
                    "401": {
                        "description": "Неверный токен (пустой, истекший или неверный формат)"
                    },
                    "404": {
                        "description": "Юзер не преподаватель, доступ запрещён"
                    }
                }
            }
        },
        "/user/me": {
            "get": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Получение всей информации о себе (юзер, профиль).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Получение информации о себе.",
                "operationId": "user-me-get",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    }
                }
            }
        },
        "/user/me/password": {
            "put": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Смена своего пароля.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Смена своего пароля.",
                "operationId": "user-me-password-update",
                "parameters": [
                    {
                        "description": "updatePasswordBody",
                        "name": "updatePasswordBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.updatePasswordBody"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "неверный старый пароль"
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    },
                    "409": {
                        "description": "пароли не должны совпадать"
                    }
                }
            }
        },
        "/user/me/profile": {
            "put": {
                "security": [
                    {
                        "JWTAccess": []
                    }
                ],
                "description": "Полное обновление своего профиля.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Обновление своего профиля.",
                "operationId": "user-me-profile-update",
                "parameters": [
                    {
                        "description": "profileBody",
                        "name": "profileBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.profileBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "401": {
                        "description": "неверный токен (пустой, истекший или неверный формат)"
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Class": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "description": "class id",
                    "type": "integer"
                },
                "name": {
                    "description": "class name",
                    "type": "string"
                },
                "schedule": {
                    "description": "class schedule",
                    "type": "string"
                },
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.User"
                    }
                },
                "teacher": {
                    "$ref": "#/definitions/entity.User"
                }
            }
        },
        "entity.Contact": {
            "type": "object",
            "required": [
                "email",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "entity.Profile": {
            "type": "object",
            "required": [
                "address",
                "contact",
                "fullname"
            ],
            "properties": {
                "address": {
                    "description": "user address",
                    "type": "string"
                },
                "contact": {
                    "$ref": "#/definitions/entity.Contact"
                },
                "extra": {
                    "description": "extra data (for admin only)",
                    "type": "string"
                },
                "fullname": {
                    "description": "user full name",
                    "type": "string"
                },
                "parent_contact": {
                    "$ref": "#/definitions/entity.Contact"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "required": [
                "id",
                "role",
                "username"
            ],
            "properties": {
                "class": {
                    "description": "student's class",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.Class"
                        }
                    ]
                },
                "id": {
                    "description": "user id",
                    "type": "integer"
                },
                "profile": {
                    "description": "user profile",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.Profile"
                        }
                    ]
                },
                "role": {
                    "description": "admin, teacher or student",
                    "type": "string"
                },
                "username": {
                    "description": "user username",
                    "type": "string"
                }
            }
        },
        "entity.UserClaims": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "user ID",
                    "type": "integer"
                },
                "role": {
                    "description": "admin, teacher or student",
                    "type": "string"
                }
            }
        },
        "v1.authBody": {
            "description": "authBody represents a data for user auth (log in).",
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "user password",
                    "type": "string",
                    "maxLength": 40,
                    "minLength": 8,
                    "example": "qwerty123"
                },
                "username": {
                    "description": "user username",
                    "type": "string",
                    "maxLength": 50,
                    "example": "user1"
                }
            }
        },
        "v1.contactBody": {
            "description": "contactBody represents a data with profile contact.",
            "type": "object",
            "required": [
                "email",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 50,
                    "example": "ivanovvp@gmail.com"
                },
                "phone": {
                    "type": "string",
                    "maxLength": 15,
                    "example": "88005553535"
                }
            }
        },
        "v1.exampleData": {
            "description": "exampleData represents an output data for example endpoints.",
            "type": "object",
            "properties": {
                "access": {
                    "description": "endpoint access description",
                    "type": "string",
                    "example": "student only"
                },
                "handler": {
                    "description": "handler name",
                    "type": "string",
                    "example": "student"
                },
                "user_claims": {
                    "description": "user claims (for endpoints with auth restriction)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.UserClaims"
                        }
                    ]
                }
            }
        },
        "v1.profileBody": {
            "description": "profileBody represents a data with user profile.",
            "type": "object",
            "required": [
                "address",
                "contact",
                "fullname"
            ],
            "properties": {
                "address": {
                    "description": "user address",
                    "type": "string",
                    "maxLength": 255,
                    "example": "3-я ул.Строителей д. 25"
                },
                "contact": {
                    "description": "user contact info",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.contactBody"
                        }
                    ]
                },
                "extra": {
                    "description": "extra data (for admin only)",
                    "type": "string",
                    "example": "только для админов"
                },
                "fullname": {
                    "description": "user full name",
                    "type": "string",
                    "maxLength": 150,
                    "example": "Иванов Василий Петрович"
                },
                "parent_contact": {
                    "description": "parent contact info (for students)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.contactBody"
                        }
                    ]
                }
            }
        },
        "v1.updatePasswordAdminBody": {
            "description": "updatePasswordAdminBody represents a data to update user password by admin.",
            "type": "object",
            "required": [
                "new"
            ],
            "properties": {
                "new": {
                    "description": "new password for user",
                    "type": "string",
                    "maxLength": 40,
                    "minLength": 8,
                    "example": "ytrewq321"
                }
            }
        },
        "v1.updatePasswordBody": {
            "description": "updatePasswordBody represents a data to update user password by the user himself.",
            "type": "object",
            "required": [
                "new",
                "old"
            ],
            "properties": {
                "new": {
                    "description": "new user password",
                    "type": "string",
                    "maxLength": 40,
                    "minLength": 8,
                    "example": "ytrewq321"
                },
                "old": {
                    "description": "old user password",
                    "type": "string",
                    "maxLength": 40,
                    "minLength": 8,
                    "example": "qwerty123"
                }
            }
        },
        "v1.userBody": {
            "description": "userBody represents a data with user.",
            "type": "object",
            "required": [
                "password",
                "profile",
                "role",
                "username"
            ],
            "properties": {
                "class_id": {
                    "description": "class id (for students)",
                    "type": "integer",
                    "example": 3
                },
                "password": {
                    "description": "user password",
                    "type": "string",
                    "maxLength": 40,
                    "minLength": 8,
                    "example": "qwerty123"
                },
                "profile": {
                    "description": "user profile",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.profileBody"
                        }
                    ]
                },
                "role": {
                    "description": "user role (teacher or student)",
                    "type": "string",
                    "enum": [
                        "teacher",
                        "student"
                    ],
                    "example": "teacher"
                },
                "username": {
                    "description": "user username",
                    "type": "string",
                    "maxLength": 50,
                    "example": "user1"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWTAccess": {
            "description": "Access JWT-token. Cookie will automatic add after auth is done.",
            "type": "apiKey",
            "name": "access",
            "in": "cookie"
        },
        "JWTRefresh": {
            "description": "Refresh JWT-token. Cookie will automatic add after auth is done.",
            "type": "apiKey",
            "name": "refresh",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "127.0.0.1:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "skadi API",
	Description:      "HTTP API онлайн-сервиса для IT-школы.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
